[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "libdrm",
  "libxkbcommon",
  "mesa",
  "pango",
  "gtk3",
  "fontconfig"
]

[phases.install]
cmds = [
  "npm install",
  "npx playwright install chromium"
]
[start]
cmd = "npm start"